### ISSUE TITLE
Go runtime server video tutorial not working for current version of nakama (v3.9.0)

### ISSUE THREAD

**Issue by Atlinx** [heroiclabs/nakama-docs#229]
I'm following [the official go runtime server tutorial](https://www.youtube.com/watch?v=Ru3RZ6LkJEk) and I'm attempting to upgrade the versions of `nakama-pluginbuilder` and `nakama` build images to v3.9.0.

I'm getting the error:
```json
{
  "level": "error",
  "ts": "2021-11-27T14:51:30.766Z",
  "caller": "server/runtime_go.go:2492",
  "msg": "Could not open Go module",
  "path": "data/modules/backend.so",
  "error": "plugin.Open(\"data/modules/backend\"): plugin was built with a different version of package google.golang.org/protobuf/internal/detrand"
}
```

Here are my relevant files:

`Dockerfile`
```dockerfile
FROM heroiclabs/nakama-pluginbuilder:3.9.0 as builder

ENV GO111MODULE=on 
ENV CGO_ENABLED 1

WORKDIR /backend
COPY go.mod .
COPY *.go ./
COPY vendor/ vendor/

RUN go build --trimpath --buildmode=plugin -o ./backend.so

FROM heroiclabs/nakama:3.9.0

COPY --from=builder /backend/backend.so /nakama/data/modules/
COPY local.yml /nakama/data
```

`docker-compose.yml`
```yml
version: '3'
services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    container_name: backend_postgres
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    expose:
      - "8080"
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - data:/var/lib/postgresql/data

  nakama:
    build: .
    container_name: backend
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama?sslmode=disable &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama?sslmode=disable
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
    links:
      - "postgres:db"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

volumes:
  data:
```

`go.mod`
```
module github.com/atlinx/nakama-server

go 1.17

require github.com/heroiclabs/nakama-common v1.20.0

require (
	github.com/golang/protobuf v1.5.0 // indirect
	google.golang.org/protobuf v1.26.0 // indirect
)
```
